-- Fix reminders table to match the entity
ALTER TABLE reminders 
ADD COLUMN IF NOT EXISTS status VARCHAR(50) DEFAULT 'PENDING',
ADD COLUMN IF NOT EXISTS priority VARCHAR(50) DEFAULT 'MEDIUM',
ADD COLUMN IF NOT EXISTS assigned_to BIGINT,
ADD COLUMN IF NOT EXISTS assigned_by BIGINT,
ADD COLUMN IF NOT EXISTS entity_type VARCHAR(50),
ADD COLUMN IF NOT EXISTS entity_id BIGINT,
ADD COLUMN IF NOT EXISTS activity_id BIGINT,
ADD COLUMN IF NOT EXISTS company_id BIGINT,
ADD COLUMN IF NOT EXISTS created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
ADD COLUMN IF NOT EXISTS updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
ADD COLUMN IF NOT EXISTS deleted_at TIMESTAMP NULL;

-- Update existing records with default values
UPDATE reminders 
SET status = 'PENDING', 
    priority = 'MEDIUM',
    assigned_to = 1,
    assigned_by = 1,
    company_id = 1
WHERE status IS NULL OR assigned_to IS NULL;
